### ISSUE TITLE
stable version? 

### ISSUE THREAD

**Issue by AlexeyMur** [Jako/WebLoginPE#3]
Sorry, is this 1.4.0 a stable version? Always get "Your photo is too big. Keep it less than 0 Kb".

**Comment by AlexeyMur** [comment]
It seems problem somewhere in webloginpe.class.php in 2391: CreateUserImage() don't get data from  $this->Options['UserImageSettings']

**Comment by Jako** [comment]
I don't maintain this code anymore, it is a fork of the original code by ScottyDelicious not available anymore including the bugfixes from MODX forums and my templating improvements (external template code). It should go into https://github.com/extras-evolution/WebloginPE if Dmytro wants this.

My improvements are described in https://github.com/Jako/WebLoginPE/blob/2dc3a11dfd1842cde3844c5c68e01e56da627092/assets/snippets/webloginpe/docs/index.html#L64-L71
